name: Ruby Gem

on:
  push:
    branches: [ "devel" ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      BUNDLE_RUBYGEMS__PKG__GITHUB__COM: ${{ github.repository_owner }}:${{secrets.GITHUB_TOKEN}}
      MONGOSQL_TEST_SQL: postgres://postgres:postgres@localhost:5432/mosql

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mosql
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      mongodb:
        image: mongo:4.0.17
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby 3.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: Build & Test
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem install bundler
          bundle config set --local deployment 'true'
          bundle install --jobs 4 --retry 3
          bundle exec rake build
          bundle exec rake install
          bundle exec rake test
      - name: Publish to GPR
        run: |
          gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} pkg/*.gem
        env:
          GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
          OWNER: ${{ github.repository_owner }}

